
version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: kapeesh
      MONGO_INITDB_ROOT_PASSWORD: kapeesh%402004

  backend:
    build: ./server
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/mydb?authSource=admin
    depends_on:
      - mongo

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo_data:
